//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowAuthoring
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Workflow.ComponentModel.Design;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Serialization;
    using System.Workflow.ComponentModel.Compiler;
    using System.Drawing;
    using System.Collections;
    using System.Workflow.Activities;
    using System.Workflow.Runtime;
    
    
    public partial class RefreshConnector : System.Workflow.Activities.SequentialWorkflowActivity
    {
        
        public static System.Workflow.ComponentModel.DependencyProperty RefreshConnectorScript_ConnectorIdProperty = DependencyProperty.Register("RefreshConnectorScript_ConnectorId", typeof(System.String), typeof(WorkflowAuthoring.RefreshConnector));
        
        public string RefreshConnectorScript_ConnectorId
        {
            get
            {
                return ((string)(base.GetValue(WorkflowAuthoring.RefreshConnector.RefreshConnectorScript_ConnectorIdProperty)));
            }
            set
            {
                base.SetValue(WorkflowAuthoring.RefreshConnector.RefreshConnectorScript_ConnectorIdProperty, value);
            }
        }
    }
}
